"""Structural interface accepted by query builders and application resources."""
from typing import Any, AsyncContextManager, List, Optional, Protocol, Sequence, Tuple

from cloudoll.orm.base import QueryTypes


class DatabaseEngine(Protocol):
    driver: str

    async def query(self, sql: str, params: Optional[Sequence[Any]] = None,
                    query_type: QueryTypes = QueryTypes.ONE, size: int = 10) -> Any: ...

    async def close(self) -> None: ...
    async def all(self, sql: str, params: Optional[Sequence[Any]]) -> List[Any]: ...
    async def one(self, sql: str, params: Optional[Sequence[Any]]) -> Optional[dict[str, Any]]: ...
    async def count(self, sql: str, params: Optional[Sequence[Any]]) -> int: ...
    async def update(self, sql: str, params: Optional[Sequence[Any]]) -> bool: ...
    async def delete(self, sql: str, params: Optional[Sequence[Any]]) -> bool: ...
    async def create(self, sql: str, params: Optional[Sequence[Any]]) -> Tuple[bool, Optional[int]]: ...
    async def create_batch(self, sql: str, params: Sequence[Sequence[Any]]) -> Tuple[int, Optional[int]]: ...


class TransactionalEngine(DatabaseEngine, Protocol):
    def transaction(self) -> AsyncContextManager["TransactionalEngine"]: ...
