import ast
from decimal import Decimal
from types import SimpleNamespace
from unittest.mock import AsyncMock

import pytest

from cloudoll.clitool.m2d import (
    create_model,
    create_models,
    create_table,
    get_col,
    get_table_cols,
)
from cloudoll.clitool.schema import compile_column, compile_table
from cloudoll.orm.field import Field
from cloudoll.orm.model import Model, models


def column(**overrides):
    return dict(
        Field="label",
        Type="varchar(120)",
        Null="YES",
        Key="",
        Default="",
        Collation="utf8mb4_general_ci",
        Extra="",
        Comment="quote ' slash \\ newline\n",
        **overrides,
    )


@pytest.mark.parametrize("driver", ["mysql", "postgres"])
@pytest.mark.parametrize(
    "value", [0, False, "", "hello('x'); DROP TABLE victim; --", "100% ' \\ \n"]
)
def test_defaults_are_bound_not_executable(driver, value):
    field = Field("value", "varchar", default=value)
    result = compile_column(field, driver)
    assert "DEFAULT ?" in result.sql
    assert result.params == [value]
    assert "DROP TABLE" not in result.sql


def test_scale_zero_and_dialect_specific_identity():
    for driver in ("mysql", "postgres"):
        result = compile_column(
            Field(
                "value", "numeric", max_length=8, scale_length=0, default=Decimal("0")
            ),
            driver,
        )
        assert "(8,0)" in result.sql
        assert result.params == [Decimal("0")]
    field = Field("id", "bigint", primary_key=True, auto_increment=True)
    assert "AUTO_INCREMENT" in compile_column(field, "mysql").sql
    assert "GENERATED BY DEFAULT AS IDENTITY" in compile_column(field, "postgres").sql


@pytest.mark.parametrize(
    "options",
    [
        dict(column_type="int); DROP TABLE x;--"),
        dict(column_type="varchar", max_length="8);--"),
        dict(column_type="numeric", max_length=2, scale_length=3),
        dict(column_type="varchar", charset="utf8mb4;DROP"),
        dict(column_type="int", default=lambda: 1),
    ],
)
def test_invalid_sql_metadata_fails_closed(options):
    with pytest.raises(ValueError):
        compile_column(Field("x", **options), "mysql")


async def test_generated_source_uses_repr_and_preserves_empty_defaults(tmp_path):
    db = SimpleNamespace(driver="mysql", all=AsyncMock(return_value=[column()]))
    source = await create_models(db, "", ["sample"])
    ast.parse(source)
    namespace = {}
    exec(source, namespace)
    field = namespace["Sample"].label
    assert field.default == ""
    assert field.comment == column()["Comment"]
    output = tmp_path / "models.py"
    await create_models(db, str(output), ["sample"])
    before = output.read_text()
    with pytest.raises(ValueError, match="already contains"):
        await create_models(db, str(output), ["sample"])
    assert output.read_text() == before


async def test_reserved_class_names_do_not_shadow_generator_imports():
    db = SimpleNamespace(driver="mysql", all=AsyncMock(return_value=[column()]))
    source = await create_models(db, "", ["model", "field", "decimal", "any"])
    namespace = {}
    exec(source, namespace)
    for name in ("ModelRecord", "FieldRecord", "DecimalRecord", "AnyRecord"):
        assert namespace[name].__fields__ == ["label"]


@pytest.mark.parametrize(
    "name", ["x-y", "class", "to_dict", "x\nexec('bad')", "_original"]
)
async def test_unrepresentable_column_names_rejected(name):
    row = column()
    row["Field"] = name
    db = SimpleNamespace(driver="mysql", all=AsyncMock(return_value=[row]))
    with pytest.raises(ValueError, match="Column name"):
        await create_model(db, "sample")


async def test_introspection_binds_postgres_names_and_quotes_mysql_identifiers():
    name = "x'`; DROP TABLE y;--"
    db = SimpleNamespace(driver="postgres", all=AsyncMock(return_value=[]))
    await get_table_cols(db, name)
    sql, params = db.all.call_args.args
    assert name not in sql and params == [name]
    assert "indisprimary" in sql and "current_schema()" in sql
    db.driver = "mysql"
    await get_table_cols(db, name)
    assert db.all.call_args.args == (
        "SHOW FULL COLUMNS FROM `x'``; DROP TABLE y;--`",
        None,
    )


def test_mysql_unsigned_precision_and_postgres_defaults():
    row = column()
    row.update(Type="decimal(9,0) unsigned", Default="0")
    result = get_col(row)
    assert (
        result["unsigned"]
        and result["scale_length"] == 0
        and result["default"] == Decimal(0)
    )
    pg = dict(
        field="name",
        column_type="character varying",
        default="'it''s (literal)'::character varying",
        null="YES",
    )
    assert get_col(pg, "postgres")["default"] == "it's (literal)"
    pg["default"] = "dangerous_function()"
    with pytest.raises(ValueError, match="default expression"):
        get_col(pg, "postgres")


async def test_preflight_all_tables_before_ddl():
    class Good(Model):
        id = models.IntegerField(primary_key=True)

    class Bad(Model):
        id = Field("id", "injected; SQL")

    db = SimpleNamespace(driver="mysql", query=AsyncMock())
    with pytest.raises(ValueError):
        await create_table(db, [Good, Bad], None)
    db.query.assert_not_called()


def test_postgres_comments_are_separate_and_bound():
    class Sample(Model):
        id = models.IntegerField(primary_key=True, comment="x'\\\n")

    statements = compile_table(Sample, "postgres")
    assert "ENGINE=" not in statements[0].sql
    assert statements[1].sql == 'COMMENT ON COLUMN "Sample"."id" IS ?'
    assert statements[1].params == ["x'\\\n"]
