@local=http://127.0.0.1:8080


### home page
GET {{local}}/ HTTP/1.1 


### get
GET {{local}}/test HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "age":20
}

### post
POST {{local}}/test HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "cloudoll"
}
