"""Real CRUD tests. Only run against explicit disposable test databases."""
import os
from uuid import uuid4

import pytest

from cloudoll.orm import create_engine
from cloudoll.orm.base import QueryTypes
from cloudoll.orm.dialects import dialect_for
from cloudoll.orm.model import Model, models
from cloudoll.orm.parse import parse_coon

pytestmark = pytest.mark.integration


@pytest.fixture(params=["mysql", "postgres", "aws-mysql", "aws-postgres"])
async def database(request):
    driver = request.param
    base = driver.removeprefix("aws-")
    url = os.getenv("CLOUDOLL_TEST_" + base.upper() + "_URL")
    if not url:
        pytest.skip("No explicit disposable test database configured")
    if driver.startswith("aws-"):
        pytest.importorskip("aws_advanced_python_wrapper")
        cfg, _ = parse_coon(url)
        cfg.update(type=driver, plugins="", wrapper_dialect="pg" if base == "postgres" else "mysql")
        db = await create_engine(**cfg)
    else:
        db = await create_engine(url=url + "?minsize=1&maxsize=2")
    try:
        yield db
    finally:
        await db.close()


async def test_real_crud_batches_group_count_and_record_binding(database):
    class Item(Model):
        __table__ = "cloudoll_test_" + uuid4().hex
        id = models.IntegerField(primary_key=True)
        category = models.VarCharField(max_length=80)
        value = models.IntegerField()

    dialect = dialect_for(database.driver)
    table = dialect.identifier(Item.__table__)
    identity = "INTEGER GENERATED BY DEFAULT AS IDENTITY" if dialect.is_postgres else "INTEGER AUTO_INCREMENT"
    await database.query(f'CREATE TABLE {table} (id {identity} PRIMARY KEY, category VARCHAR(80), value INTEGER)', query_type=QueryTypes.UPDATE)
    try:
        success, identity = await Item.use(database).insert(category="first", value=1)
        assert success and identity is not None
        row = await Item.use(database).where(Item.id == identity).one()
        assert isinstance(row, Item)
        assert row.get("value") == 1
        row.value = 2
        assert await row.update()
        await Item.use(database).insert_batch([
            {"category": "batch", "value": 3}, {"value": 4, "category": "batch"},
        ])
        assert await Item.use(database).count() == 3
        assert await Item.use(database).group_by(Item.category).having(Item.value.sum() > 4).count() == 1
        assert await Item.use(database).where(Item.id.In([])).all() == []
        assert await Item.use(database).where(Item.category == None).all() == []
        assert len(await Item.use(database).order_by(Item.id.asc()).offset(1).all()) == 2
        query = Item.use(database).where(Item.category == "batch")
        assert (await query.clone().count()) == 2
        assert len(await query.all()) == 2
        assert await row.delete()
        assert await Item.use(database).count() == 2
        with pytest.raises(Exception):
            await database.one("SELECT missing_column FROM " + table, None)
        assert await Item.use(database).count() == 2
    finally:
        await database.query("DROP TABLE " + table, query_type=QueryTypes.UPDATE)
