server:
  host: 127.0.0.1
  port: 9001
  ignore_dirs: ["logs", "test"]
  client_max_size: 10000
  static:
    prefix: /static

# database:
#   mysql_db:
#     url: mysql://username:password@host:port/database
#     echo: false  # SQL debug logging (INFO)
#     echo_params: false  # Requires echo; may expose sensitive values
#   postgres_db:
#     url: postgres://username:password@host:port/database
#     echo: false
#     echo_params: false
#   redis_0:
#     url: redis://host:port:/0

# session:
#   max_age: 604800
#   secret_key: $CLOUDOLL_SESSION_SECRET
#   redis: redis://host:port/0
#   memcached:
#     host: 192.168.1.100
#     port: 11211

jwt:
  key: $CLOUDOLL_JWT_SECRET
  exp: 604800
